name: Java workflow

on:
  push:
    branches:
      - java
  pull_request:
    branches:
      - java

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Super-Linter
        uses: github/super-linter@v4
        continue-on-error: true
        env:
          VALIDATE_JAVA: true
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Capture output from the linting tool
        if: always()
        run: |
          mkdir -p logs
          docker logs ${{ steps.linter.outputs.linter_id }} > ./logs/lint-results.log

      - name: Upload lint results
        uses: actions/upload-artifact@v2
        with:
          name: lint-results
          path: logs/lint-results.log
          
      - name: Build, using mvn
        run: mvn clean install
        working-directory: ./java-calc

      - name: Run unit tests
        run: mvn test
        working-directory: ./java-calc

      - name: Fetch tags and branches
        run: git fetch --prune --unshallow

      - name: Bump version and tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          default_bump: patch
          release_branches: java

      - name: Output new version
        run: echo "The new version is ${{ steps.tag_version.outputs.new_tag }}"
