name: Java workflow

## Adding permissions, because of CodeQL

permissions:
  contents: read
  security-events: write

on:
  push:
    branches:
      - java
  pull_request:
    branches:
      - java

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      ## Code formatting, using Google Java Format

      - name: Install Google Java Format
        run: |
          wget https://github.com/google/google-java-format/releases/download/google-java-format-1.9/google-java-format-1.9-all-deps.jar
          echo "Google Java Format installed."

      - name: Format Java code
        run: |
          find java-calc/src -name "*.java" -exec java -jar google-java-format-1.9-all-deps.jar --replace {} +

      ## Linting, using Checkstyle

      - name: Install Checkstyle
        run: |
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-9.0/checkstyle-9.0-all.jar
          echo "Checkstyle installed."

      ## Create logs directory and upload the logs after the linting tool has scanned the code
       
      - name: Create logs directory
        run: mkdir -p logs

      - name: Run Checkstyle
        run: |
          java -jar checkstyle-9.0-all.jar -c /google_checks.xml ./java-calc/src > ./logs/checkstyle-results.log    

      - name: Upload lint results
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: logs/checkstyle-results.log

      - name: Build, using mvn
        run: mvn clean install
        working-directory: ./java-calc

      - name: Run unit tests
        run: mvn test
        working-directory: ./java-calc

      - name: Fetch tags and branches
        run: git fetch --prune --unshallow

      - name: Bump version and tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          default_bump: patch
          release_branches: java

      - name: Output new version
        run: echo "The new version is ${{ steps.tag_version.outputs.new_tag }}"

  codeql-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Build the project for CodeQL
        run: mvn clean install -DskipTests
        working-directory: ./java-calc

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
